//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ca_asiento
    {
        public ca_asiento()
        {
            this.ma_cinetmaz = new HashSet<ma_cinetmaz>();
        }
    
        public int cve_asiento { get; set; }
        public Nullable<int> numero_asiento { get; set; }
        public Nullable<int> estatus_asiento { get; set; }
    
        public virtual ICollection<ma_cinetmaz> ma_cinetmaz { get; set; }
    }
}
