//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ca_sala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ca_sala()
        {
            this.ca_pelicula = new HashSet<ca_pelicula>();
        }
    
        public int cve_sala { get; set; }
        public string nombre_sala { get; set; }
        public int capacidad_sala { get; set; }
        public int cveclasificacion_sala { get; set; }
    
        public virtual ca_clasificacion ca_clasificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ca_pelicula> ca_pelicula { get; set; }
    }
}
