//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ca_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ca_usuario()
        {
            this.ca_cliente = new HashSet<ca_cliente>();
            this.ca_cliente1 = new HashSet<ca_cliente>();
        }
    
        public int cve_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string user_usuario { get; set; }
        public string password_usuario { get; set; }
        public System.DateTime fechacreacion_usuario { get; set; }
        public int cveestatus_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ca_cliente> ca_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ca_cliente> ca_cliente1 { get; set; }
        public virtual ca_estatus ca_estatus { get; set; }
    }
}
