//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ca_usuario
    {
        public ca_usuario()
        {
            this.ma_cinetmaz = new HashSet<ma_cinetmaz>();
        }
    
        public int cve_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public string apepaterno_usuario { get; set; }
        public string apematerno_usuario { get; set; }
        public int edad_usuario { get; set; }
        public int estatus_usuario { get; set; }
        public int cveusuarioalta_usuario { get; set; }
        public System.DateTime fechaalta_usuario { get; set; }
        public Nullable<int> cveusuariomod_usuario { get; set; }
        public Nullable<System.DateTime> fechamod_usuario { get; set; }
    
        public virtual ICollection<ma_cinetmaz> ma_cinetmaz { get; set; }
    }
}
