//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_cinetmaz
    {
        public int cve_cinetmaz { get; set; }
        public int cvecliente_cinetmaz { get; set; }
        public int cvepelicula_cinetmaz { get; set; }
        public int cveasiento_cinetmaz { get; set; }
    
        public virtual ca_cliente ca_cliente { get; set; }
        public virtual ca_pelicula ca_pelicula { get; set; }
        public virtual ca_asiento ca_asiento { get; set; }
    }
}
