//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CinetmazEntities : DbContext
    {
        public CinetmazEntities()
            : base("name=CinetmazEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ca_clasificacion> ca_clasificacion { get; set; }
        public DbSet<ca_asiento> ca_asiento { get; set; }
        public DbSet<ca_pelicula> ca_pelicula { get; set; }
        public DbSet<ca_sala> ca_sala { get; set; }
        public DbSet<ca_cliente> ca_cliente { get; set; }
        public DbSet<ma_cinetmaz> ma_cinetmaz { get; set; }
    
        public virtual int spAgregarClasificacion(string tipo, Nullable<int> edadMinima, string descripcion)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var edadMinimaParameter = edadMinima.HasValue ?
                new ObjectParameter("edadMinima", edadMinima) :
                new ObjectParameter("edadMinima", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAgregarClasificacion", tipoParameter, edadMinimaParameter, descripcionParameter);
        }
    }
}
