//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMostrarTodosPelicula
    {
        public int Clave { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.TimeSpan> Duración { get; set; }
        public Nullable<int> cvegenero_pelicula { get; set; }
        public string Genero { get; set; }
        public int cvesala_pelicula { get; set; }
        public string Sala { get; set; }
        public string Clasificación { get; set; }
        public byte[] portada_pelicula { get; set; }
    }
}
